Vagrant.configure("2") do |config|

  config.vm.box = "ubuntuPuppetLabs"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"

  config.vm.hostname = "logserver"
  config.vm.network :private_network, ip: "192.168.33.7"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
  end
  
  config.vm.provision :puppet,
	:facter => { "fqdn" => "logserver.blog.fr" }  do |puppet|
	puppet.puppet_node = "logserver.blog.fr"
	puppet.module_path = "../modules"
    puppet.manifests_path = "../manifests"
    puppet.manifest_file  = "site.pp"
	puppet.options = "--verbose --fileserverconfig=/vagrant/fileserver.conf"
  end

end
